import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev.mirrix.app/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('lakshmi@unitofmeasure.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Welcome@123');
  await page.locator('svg').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Upload' }).click();
  await page.getByRole('button', { name: 'Select files', exact: true }).click();
  await page.getByRole('button', { name: 'Select files', exact: true }).setInputFiles('61tmTIwEdnL._AC_UF1000,1000_QL80_.jpg');
  await page.getByText('Batch File UploadUpload').click();
  await page.getByText('Default').click();
  await page.getByText('Images', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Upload Batch Description:' }).click();
  await page.getByRole('textbox', { name: 'Upload Batch Description:' }).fill('Test_image');
  await page.locator('.ant-tag').click();
  await page.getByRole('textbox').nth(1).fill('doll');
  await page.getByRole('textbox').nth(1).press('Enter');
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Select files', exact: true }).click();
  await page.getByRole('button', { name: 'Select files', exact: true }).setInputFiles('61tmTIwEdnL._AC_UF1000,1000_QL80_.jpg');
  await page.getByText('Default').click();
  await page.getByText('Images', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Upload Batch Description:' }).click();
  await page.getByRole('textbox', { name: 'Upload Batch Description:' }).fill('Test_image_0904');
  await page.locator('.anticon.anticon-plus > svg').click();
  await page.getByRole('textbox').nth(1).fill('doll');
  await page.getByRole('textbox').nth(1).press('Enter');
  await page.getByRole('button', { name: 'Upload', exact: true }).click();
  await page.getByRole('button', { name: 'Drag your file(s) to start' }).click();
  await page.getByText('Uploading... 100%').click();
  await page.getByRole('cell', { name: '4/9/' }).click();
  await page.getByRole('cell', { name: 'BGP_146302' }).click();
  await page.getByRole('cell', { name: '61tmTIwEdnL._AC_UF1000,' }).click();
  await page.getByRole('cell', { name: 'IMG_146303' }).click();
  await page.getByRole('cell', { name: 'Completed' }).first().click();
  await page.getByRole('cell', { name: 'eye Preview' }).first().click();
  await page.locator('.ant-image-preview-img').click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.getByRole('link', { name: 'IMG_146303' }).click();
  await page.getByRole('list').getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByText('61tmTIwEdnL._AC_UF1000,1000_QL80_Uploaded: 2026-04-').click();
  await page.locator('.w-full.justify-between').first().click();
  await page.getByRole('img', { name: 'thumb' }).first().click();
  await page.getByRole('list').getByRole('link').filter({ hasText: /^$/ }).click();
});
